from docx import Document
from docx.shared import Inches
import pyttsx3


def speak(text):
    pyttsx3.speak(text)

document = Document()
# profile picture
document.add_picture('profile.jpeg', width=Inches(2.0))

# name phone number and email details
first_name = input('What is your first name? ')
last_name = input('What is your last name? ')
speak('Hello ' + first_name + last_name + '  how are you today? ')
speak('What is your phone number')
phone_number = input('What is your phone number? ')
email = input('What is your email? ')

document.add_paragraph(
    first_name + ' ' +  last_name + ' | ' + phone_number + ' | ' + email)

#about me
document.add_heading('About me')
about_me = input( 'Say something about youself? ')
document.add_paragraph(about_me)

#work experience
document.add_heading(' Work Experience ')
p = document.add_paragraph()

company = input (' Enter Company: ')
from_date = input(' From date: ')
to_date =  input(' To date: ')

p.add_run(company + ' ').bold = True
p.add_run(from_date + '-' + to_date + '\n').italic = True

experiece_details = input(' Describe your experience at ' + company + ':')

p.add_run(experiece_details)


#more experiences
while True:
    has_more_experiences = input(
        'Do you have more experiences? Yes or No? ')
    if has_more_experiences.lower() == 'yes':
        p = document.add_paragraph()

        company = input (' Enter Company: ')
        from_date = input(' From date: ')
        to_date =  input(' To date: ')

        p.add_run(company + ' ').bold = True
        p.add_run(from_date + '-' + to_date + '\n').italic = True

        experiece_details = input(' Describe your experience at ' + company + ':')

        p.add_run(experiece_details)

    else:
       break
    
    
    #skills
document.add_heading('Skills')
skill = input('Enter your skill: ')
p = document.add_paragraph(skill, style='List Bullet')

while True:
    has_more_skills = input('Do you have more skills? Yes or No? ')
    if has_more_skills.lower() == 'yes':
        skill = input('Enter your skill: ')
        document.add_paragraph(skill, style="List Bullet")
    else:
         print('Good!Your CV is waiting for you!')
         break
     
    
    #footer
    section = document.sections[0]
    footer = section.footer
    p = footer.paragraphs[0]
    p.text = 'CV generated by theo trg '


document.save('cv.docx')



